name: ReputationBGS
version: '${project.version}'
main: me.remag501.reputation.Reputation
api-version: '1.21'
depend: [PlaceholderAPI]

commands:
  reputation:
    description: Manage player reputation
    usage: /<command> <add|remove|set|view>
    permission: reputation.use
