name: ${project.name}
version: '${project.version}'

main: me.remag501.reputation.ReputationPlugin
api-version: '1.21'
depend: [BGSCore, PlaceholderAPI]

commands:
  reputation:
    description: Manage player reputation
    usage: /<command> <add|remove|set|view>
    permission: reputation.use
